// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArkFXwJT7v7DYsZFFQmyGGn9icA2b7zjY',
    appId: '1:237026644296:web:474b46b5069ec4fcc9a37d',
    messagingSenderId: '237026644296',
    projectId: 'squeezit-dsi34',
    authDomain: 'squeezit-dsi34.firebaseapp.com',
    storageBucket: 'squeezit-dsi34.firebasestorage.app',
    measurementId: 'G-4F7QR3S46J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnY76NTWMyzE5yYZsVEG5yJsTM2U00NsI',
    appId: '1:237026644296:android:e08bf325e14e5625c9a37d',
    messagingSenderId: '237026644296',
    projectId: 'squeezit-dsi34',
    storageBucket: 'squeezit-dsi34.firebasestorage.app',
  );

}